# Generated by Django 4.2.5 on 2023-09-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_voteuser_school_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('question', 'user')},
        ),
    ]
