# Generated by Django 4.2.5 on 2023-10-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
