# Generated by Django 4.2.5 on 2023-12-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_gender_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='genders'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
