# Generated by Django 4.2.5 on 2023-12-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_gender_image_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='image',
        ),
        migrations.AddField(
            model_name='gender',
            name='sf_symbol',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
