# Generated by Django 4.2.5 on 2023-12-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_gender_image_gender_sf_symbol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='sf_symbol',
            new_name='emoji',
        ),
    ]
