# Generated by Django 4.2.5 on 2024-01-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_question_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='show_creator',
            field=models.BooleanField(default=True),
        ),
    ]
